Fix emulated PAK files missing padding at the end
Sewer56/FileEmulationFramework pull request #17
Opened 2024-04-20 06:11 UTC by AnimatedSwine37

Pak files should have an additional empty entry header at the end of them, this adds that.

This was found to cause crashes in P3P, mainly when editing init_free.bin as it is loaded at boot when there is a decent chance the memory after the file is unallocated.

Looking at pak files from P5R and P4G it seems that all versions of the format probably expect this additional header so I've added it for all three. Those games seemingly not crashing may be due to them handling the erroneous file better (just speculation, P3P is the only game I properly looked at).

2024-04-20 15:57 UTC, Sewer56 requested changes
Allocating a new array zeroes the contents to the default value, in which case it means the array is already zeroed. There is no need to zero it again.

There's also a MemoryStream constructor which accepts an existing buffer. So simply create the array, and pass it to MemoryStream's constructor which lets you pass byte array.

2024-04-21 00:07 UTC, Sewer56 approved these changes

2024-04-21 00:07 UTC, AnimatedSwine37 commented
I did that as some existing code in PakBuilder did so I assumed it was the way to go. I've updating both the existing and new code like you said.

2024-04-21 00:07 UTC, merged

2024-04-21 00:10 UTC, Sewer56 commented
All sorted, with release out too.